### ISSUE TITLE
Determine best way to test pyrostest.

### ISSUE THREAD

**Issue by joshuamorton** [gtagency/pyrostest#10]
There's a bit of a conundrum with testing this. We'll need CI, but I think the best way to test this will be to create a rospackage for testing that this deploys when we want to actually test, which is horrendous and mildly frankenstinian, but I can't think of anything better.

To be more concrete, a `tests/` dir with tests and also a `rospack` subdir which contains a ros package that is deployed to catkin_ws by our CI script.

**Comment by joshuamorton** [comment]
Thoughts? @iRapha

**Comment by iRapha** [comment]
The cleanest solution at first seems to be using simple unit tests that would check whether, for instance, a class that inherits `RosTest`, make sure it's setUp and tearDown are being correctly modified. However, it becomes obvious that this solution is terrible when you consider the details of what this framework does (what with spinning up ros instances in separate threads, and all).

Therefore, I'm in favor of having a test rospackage that we can spin up for testing. The cleaner version of that is having multiple packages that are specific to each test, but that easily becomes unmaintanable too.

For such a package, we can have nodes that do generic things like:

- `pub_rand_int_1hz` - publishes random int at 1hz
- `pub_inc_int_1hz` - publishes incrementing int at 1hz
- `sub_int_passover_pub` - subscribes to an int topic, and publishes every message it receives
- `spin` (just inits node and spins)

Note I haven't put much thought into these examples, but they are things we can work off of.

**Comment by joshuamorton** [comment]
This was more or less my plan, have some nodes that publish things in that
manner, and then a couple that do simple operations, like add a number.
