### ISSUE TITLE
fix listener.py and subscriber.py

### ISSUE THREAD

**Issue by joshuamorton** [gtagency/pyrostest#4]
They currently rely on a directory, we should fix that.

**Comment by iRapha** [comment]
More information, from the original issue: https://github.com/gtagency/buzzmobile/issues/185

```
Currently mock_node and check topic will fail if tests are run from the wrong directory because the paths to listener and publisher are hardcoded. Lets fix that shall we.
```

**Comment by joshuamorton** [comment]
Manually tested on pyrostest-test branch of buzzmobile, until we can get some better tests here.
