### ISSUE TITLE
Clean up naming conventions.

### ISSUE THREAD

**Issue by joshuamorton** [gtagency/pyrostest#5]
There are some bad naming conventions throughout. We should improve that.

**Comment by iRapha** [comment]
Can you be more specific? I thought the api naming was alright

**Comment by joshuamorton** [comment]
internally, `publisher` and `listener` should be publisher and subscriber.

Externally,`mock_node` might be better as say, and `mock_topic` or `mock_message(s)`

**Comment by iRapha** [comment]
Fair point, agreed
